/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09.threadtests;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        var dummy = new Dummy();

        dummy.doImportantStuff1();
        dummy.doImportantStuff2();
        dummy.doImportantStuff3();

        System.out.println("The end");
    }
}
