/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09.threadtests;

public class AppWithThreads {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException {
        System.out.println(Thread.currentThread().getName());

        var importantStuff1 = new ImportantStuff1();
        var importantStuff2 = new ImportantStuff2();
        var importantStuff3 = new ImportantStuff3();

        importantStuff1.start();
        importantStuff2.start();
        importantStuff3.start();

        importantStuff1.join();
        importantStuff2.join();
        importantStuff3.join();

        System.out.println("The end");
    }
}
