/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09.threadtests;

public class AppWithThreads {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException {
        System.out.println(Thread.currentThread().getName());

        var importantStuff1 = new ImportantStuff1();
        var importantStuff2 = new ImportantStuff2();
        var importantStuff3 = new ImportantStuff3();

        var thread1 = new Thread(importantStuff1);
        var thread2 = new Thread(importantStuff2);
        var thread3 = new Thread(importantStuff3);

        thread1.start();
        thread2.start();
        thread3.start();

        thread1.join();
        thread2.join();
        thread3.join();

        System.out.println("The end");
    }
}
